### ISSUE TITLE
All the documentation removed?

### ISSUE THREAD

**Issue by yohcop** [foxdonut/meiosis#26]
Hi,
What happened in https://github.com/foxdonut/meiosis/commit/a04e86d226531ab04d4cf29e92628c3a5fb96f76 ? Why was all the documentation removed?

**Comment by foxdonut** [comment]
Hi @yohcop 

I updated the [Meiosis Tutorial](https://meiosis.js.org/tutorial/toc.html). The core pattern is the same, but the approach is simpler and makes more idiomatic use of view libraries.

Because of this simpler approach, some of the articles in the documentation are redundant; some are outdated; and some solve problems that are no longer problems at all.

Thus, I need to update the documentation, and this is [in progress](https://meiosis.js.org/docs/toc.html). In the meantime, I did not want to leave the old documentation because it would lead to confusion.

I hope that makes sense.
