### ISSUE TITLE
Tutorials for react deleted 

### ISSUE THREAD

**Issue by kanglicheng** [foxdonut/meiosis#27]
Not so much an issue but more of a question, why have all the react related tutorials been deleted? I actually found them helpful.

**Comment by foxdonut** [comment]
@kanglicheng the tutorial itself has been reorganized to be simpler. It is no longer necessary to have a separate React series because the pattern is independent of the view library until it is time to wire it. For React this is explained in [08 - Using React](http://meiosis.js.org/tutorial/08-using-react.html).

Also, the way that it is wired is more idiomatic to React, making it simpler to use React components, lifecycle methods, and so on.

Does that help?
