### ISSUE TITLE
API observation (minor nit)

### ISSUE THREAD

**Issue by mnichols** [foxdonut/meiosis#3]
Hey @foxdonut ... as i am getting further along with meiosis, one odd thing to me about the API is the `nextAction` function declaration `(model, proposal, actions)`.
In _most_ cases, only the `model` and `actions` would be needed to make a decision on the next Action I think so requiring that the dev declare all three args to get the `actions` (which he will surely need for a nextAction) seems to miss out on the benefits of JS where I could just do something like `nextAction: (model, actions) => { if(model.foo) { actions.go('foo') }}`
I know the proposal can inform the context of the request/loop but as far as I have learned that isnt as common as just reading model state to decide what's next. Is that wrong? I dont want to be frivolous.

**Comment by foxdonut** [comment]
@mnichols I agree with you. In some places of the API, I find the parameters to be "natural" and easy to remember, for example `view(model, actions)`. Not so with `nextAction`, and as you said, only one or two of the three parameters are needed, probably most of the time.

Instead of changing the order of parameters, I'm thinking of making it a single object parameter. Then you could write `({model, actions}) => ...` or `({proposal, actions}) => ...` to pick out what you need, and without worrying about the order of the parameters.

What do you think?

Thanks again.

**Comment by mnichols** [comment]
@foxdonut I _always_ favor a single 'spec' parameter that I can deconstruct in APIs I build, so yes I'd agree with your direction.
The only place where it _might_ be inconvenient to adopt that convention universally in this project  would be inside the actual render function from the component, eg:
`cfg.view(state, actions)` => `cfg.view({ state, actions })`. 
The only reason that approach would be slightly inconvenient is because it is so common to deconstruct props inside the function for a react component, eg:
`function MyView({ name, id}, actions) {...}`. It is a minor nit but the dev would need to deconstruct from a `state` param if you take the single spec approach there.
Otherwise, yes I find scaling out APIs is better when passing in a single spec object instead of trying to  play parameter games. For example, maybe later you want to support providing a `context` param inside the `state` func. That'd be alot easier with less breaking changes if user always deconstructed His Things.

**Comment by foxdonut** [comment]
The new version of Meiosis gives you a lot more flexibility to decide what parameters to pass to your functions.
