### ISSUE TITLE
SAM Pattern nap issue

### ISSUE THREAD

**Issue by Dkendal** [foxdonut/meiosis#30]
First of I want to say thank you for writing all of this content, I've found it to be a tremendous resource.

When implementing  a system that uses a next-action function I discovered that the system generates many duplicate events given the example implementation.

``` js
nap: actions => state => {
  if (state.pageId === "DataPage" && !state.data) {
    actions.loadData();
  }
}

const present = flyd.stream();
const actions = app.actions(present);
const states = flyd.scan(app.acceptor, app.initialState(), present)
  .map(app.state);
states.map(app.nap(actions));
```

Adding additional actions will result in `n!` calls to nap, state, and anything downstream as a function of the number of `updates` in the `actions`. This was easily fixed by tweaking the example using a stream combinator. The previous example then becomes:

``` js
nap: actions => state => {
  if (state.pageId === "DataPage" && !state.data) {
    actions.loadData();
  }
}

const present = flyd.stream();

const actions = app.actions(present);

const computed = flyd.scan(app.acceptor, app.initialState(), present)
  .map(app.state);

const states = flyd.combine(
  (computed) => {
    if (!app.nap(actions)(computed())) {
      // If nap indicates that there was no action called then create a new
      // event. This prevents nap from triggerring the same action
      // several times.
      return computed();
    }
  },
  [computed],
);
```

I derived this solution from the [sam.js](http://sam.js.org/#model) docs. With this small tweak a new state isn't produced and rendered if a next action was triggered.

Thanks again!

**Comment by foxdonut** [comment]
@Dkendal 

> First of I want to say thank you for writing all of this content, I've found it to be a tremendous resource.

Thank you for the kind words, that is great to hear!

> `if (!app.nap(actions)(computed())) {`

That is a good observation. I too noticed the difference with the next-action predicate on the [SAM web site](https://sam.js.org). As you said, there the `nap` function returns a boolean indicating whether an action was triggered, and the view only gets returned when no action was triggered:

```javascript
if (!nap(sr)) {
  // Render the view when no next action is invoked
  view.render(sr)
}
```

One reason for my different approach is that in my case, the next action, a.k.a. services, may trigger actions asynchronously. Thus they are functions that return `void` and (possibly) trigger synchronous or asynchronous updates.

Another important reason is that the action being triggered may be to set a "please wait" indicator, for example. So, in fact we do not want to prevent re-rendering in that case, even though `nap()` did indeed trigger an action.

Only if actions trigger an `update` does the view re-render. This is what we want, because we want the view to reflect the current state. If there is anything _synchronous_ that needs to be in the state before it is rendered, that belongs in the SAM `State` / Meiosis `computed` function.

Finally, note that `nap()` / services trigger on a condition, and it is their responsibility to trigger updates that avoid infinite loops. Checking these conditions will be very fast, so the fact that multiple services are triggered should not be a performance concern. Same goes for re-rendering, since the virtual-DOM library only updates the view with what has changed.

I hope that helps! Cheers.

**Comment by smuemd** [comment]
@foxdonut I came to the same realisation. The trigger condition(s) is/are really key, I found. I guess the important thing is to avoid triggering multiple service updates for a given view / page, since services/naps are not really compostable as such. I had React barking at me several times when multiple update calls fired from services. It's a bit of a footgun that people should be made aware of down the line.

Overall your simplification of the patterns works really well. I converted a semi complex app to the new pattern. it's all improvements and no drawbacks so far. 👍

**Comment by foxdonut** [comment]
@smuemd excellent, thank you very much!

**Comment by foxdonut** [comment]
@Dkendal just FYI, I am currently working on an improved setup which includes a [reduced number of calls](https://github.com/foxdonut/meiosis/blob/update-actions-lens/helpers/setup/common/setup.js#L104) to acceptors and services. I will be publishing this soon and will update the docs on services and the SAM pattern.

**Comment by Dkendal** [comment]
Neat! Our design has significantly diverged at this point as I had a couple other design considerations that I wanted to promote; namely isolating and managing effects and removing implicit constraints (like reducers have to call update, calling update multiple times results in multiple passes through nap, etc.). I'm hoping that we'll be able to open source some of it or at least detail the approach to give back here :).

**Comment by foxdonut** [comment]
@Dkendal indeed I'm also combining multiple `update` calls into a single pass as well.

Please do share your design when you have the chance.
