### ISSUE TITLE
Feature request: bind actions to Actions object

### ISSUE THREAD

**Issue by avionbg** [foxdonut/meiosis#45]
Basically, adding this to the common.js before exporting everything;
```js
  const bindActions = Object.entries(actions).reduce((acc, [key, func], index) => {
    acc[key] = func.bind(actions)
    return acc
  }, {})

  return { update, contexts, states, actions: bindActions }
```
This way we can call actions from inside actions with simple `this.action`. It would be a nice addition since you can include more logic between the actions inside them.
I have something similar, basically :
```
Actions : {
   api : { /* ... */ }
   paging: { /* ... */ }
   sorting: { /* ... */ }
}
```
where paging and sorting are internally calling the api action, and so on ...

**Comment by foxdonut** [comment]
@avionbg indeed this looks like it could be a nice addition, I will try it out. Thanks!

**Comment by foxdonut** [comment]
@avionbg finally got a chance to try this out. Seems to be working without needing to make any changes. Please see [this example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9ACoJAAgAC-AB7SADgCcYGasSLSJYgDppJ0gOZRaAIwxRpAWRgRacCHAp2HTlwCVaAV2IQaCa6BmgQWMq0qsQq6poxYKq0WNL6IGoaWrIAHPgALPgATGIAJi7EYhnx+Fj8aQDchuGR0dI4qiYw0onJqSDtnaqBtLIADPn4ow2GhkJwMQCCWo5ocACM0gC80r7KJRiMWwB80gAUwIbS0oHU6jgMiGcAlMc7ewcw59J0vg-SSpsTkoANTSDasJ6GCGNNCzejzaRLALwwpbN77Q6As4XNBXQKMVTxR5gX7LeinF44q5XXYYz7Aa7CQlktCPAEnACESmhl2pxEILnwNzuIgpMKurChkNhaDmMQwymUaKpjIgAWsjwZPz+ozc+JgzORrO61jgXXYvKRKzgj1pH1eAHkLLwYFp8Bg4M4TGhTryrsALbjqVb4WtTnbGE8KH7ESy4IVw+9I7zpawYXDVjEGfMPq5pPFrdJWGj7I5nHAagbBsN8GbiLtzrz5nEsI9S54K84IrAAMrEFvRoMDGCDq4K5RS9Oy+ExHy0GLbL45xhuAvwosvLEq9T11S431Bq4AHjKADcjjHj2ejgBhPxMzXLmD4bXEVhH0oQc+X6Qnr9HABJJk12NYA+yGIJTifIVgJZJ530-b9D2pP9zyPCx-GIehpHoG8oAgagAGtNmAClXhAit9UNClWFvfCiLaGAPww4gsLQI4P2vGNOP-FMYTTGZp0zRFFRLDxy3wKo3TrBsGSk4g3DnGIeRleT8HUNASgNA9jwWUSnzgEiDOLCiSIo4sxCOUdpBKWhqF8e5tAsWgSgAT0MJ4YUoGhkmUaADTwKwLBgcgqDNWA4zwNZCkQUYAFo1gAZlitgOBATAcDwF9PW8oRGGYHg2AAXSofC0EIhAUE4TKeBwMsXDimTlHwfhvN8VRyB4EhiGUG0xDEX5lEIkwX2SMQ6o7RqYHrZRZES-A1kmT95nG8SGqalqBBAYhXOUbgQDgW4IGUURWBK9KuDwdty1jI0EFYIA). If you use `function() { ... }` instead of `() => { ... }`, an action can call another action with `this.otherAction()`.

What do you think?

**Comment by foxdonut** [comment]
Further, you cannot bind `this` for arrow functions, as you can see [here](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4A9ACoJAAgAC-AB7SADgCcYGasSLSJYgDppJ0gOZRaAIwxRpAWRgRacCHAp2HTlwCVaAV2IQaCa6BmgQWMq0qsQq6poxYKq0WNL6IGoaWrIAHPgALPgATGIAJi7EYhnx+Fj8aQDchuGR0dI4qiYw0onJqSDtnaqBtLIADPn4ow2GhkJwMQCCWo5ocACM0gC80r7KJRiMWwB80gAUwIbS0oHU6jgMiGcAlMc7ewcw59J0vg-SSpsTkoANTSDasJ6GCGNNCzejzaRLALwwpbN77Q6As4XNBXQKMVTxR6nF5YnFXK67DGfYDXYSE5b0R4Ak4AQiU0MuFOIhBc+BudxEJJhV1YUMhsLQcxiGGUyjR5LpEAC1ketJ+f1GbnxMAZyLQjzA1jgXXYXKRKzgjypH1eiqu0uk8UtaIA8hZeDAtPgMHBnCY0KcuRTpMAzbiQ4jGas1qcbYwnhRgxSLSi4+8E8mJSHHRZAiVU6s3R6vdoREN4KdnfCnvh1CVfNRPlXqNQ3MgANYwACebjAv2oAF1SSd7RTNNROz3B2j+1L8Hm0CUW-q4E8RZH1MRfKpcRON6K3GHsxStzvcYuC9G4BuxWhWDC4asYrT5h9XE7r9JWGj7I5nHANS6oMwz4Ca27KOcXLzHEWCPH+niAc4ESwAAysQsFJhGAwwFhVyyso4qPlK8IxD4tAxNsXxvowbjVkWEJ2lyZ67mcyYADxlAAbkcyZXJxEA8QAwn49JqjRMD4BqxCsOxpSCbxEYhgJPEAJL0vRaroUMQSnBJ-IadGTyyfJPF8dIKlHOxFj+MQ9DSPQQlQBA1AdpswAkq89GATqeokqwRxOS5HZtDAck2cQdloFZpmKcpsVcuuULEY6Cxyr+HgAfgVTeuBuxfDlxBuORMScpKhV1kwJS6kGEbsWl8oSXA7lNT+3nud5P5iEceHSCUtDUL49zaBYtAlN2hhJWglA0MkyjQLqeBWBYMDkFQJqwNeeBrIUiCjGwHAgJgOB4FJfozUIjDMDwbCDlQzloB2CAoJwJ08Dg-4uAAtHlyj4PwM07uQPAkMQyhWmIYi-MoHYmFJyRiB9iE-TAEGyAAzPgayTPJ8yI5l32-f9AggMQ3bKNwIBwLcEDKKIrB3UdXB4AhAFRqubBAA).
