### ISSUE TITLE
Use of object.assign() in chapter 8

### ISSUE THREAD

**Issue by mindplay-dk** [foxdonut/meiosis#8]
I can see why it doesn't matter in this particular example, but using `object.assign()` directly does actually have the side-effect of changing the existing value of the stream, while returning the same mutated object rather than a new one.

The stream isn't strictly a "stream" anymore - it's now a "stream-looking" way of performing continuous operations on mutable state, which is a bit confusing and likely could lead to bugs in more complex scenarios? 🤔

Likely the appropriate function would be something like:

    function(model, value) {
      return Object.assign({}, model, value);
    }

Which is side-effect free.

I understand it doesn't lead to problems in this particular case, but you are trying to teach people functional programming patterns, where typically functions are kept pure and free of side-effects?

I'm by no means an expert, it just occurred to me that some people might not understand that using `object.assign()` in this way, with FRP patterns, in general, isn't really safe?

**Comment by foxdonut** [comment]
Excellent points!

You are correct, we are mutating the object, and we have set up a controlled way of re-rendering the view on the same object, using streams to control when the re-rendering occurs.

Later on, when using a stream of functions for updates, the nesting function is:

```js
var nestUpdate = function(update, prop) {
  return function(func) { // this is the nested update. take the incoming func, and
    update(function(model) { // call the original update, and
      model[prop] = func(model[prop]); // call func on the nested model
      return model;
    });
  };
};
```

Again, we are mutating `model` and returning it.

The Meiosis pattern works well both with mutation and immutable objects. Because we have set up a clear, unidirectional reactive loop, mutation is unlikely to cause bugs. I did not want to prescribe immutability because it is not required for the pattern to work well.

`Object.assign` is used to gradually explain the concept of a stream of updates, working our way up to using a stream of functions for updating the model. Once reached, utilities such as Ramda and Lodash-FP can help with producing new objects instead of mutating existing ones. I have sections on these libraries in the [Wiki](http://meiosis.js.org/wiki/toc.html). But again, I don't want to imply that immutability is a requirement.

As you said, there are some functional programming patterns that rely on immutable objects. Indeed I am trying to teach some FP concepts because they are useful with Meiosis, but there's nothing wrong with using mutation.

Thank you for your feedback, I appreciate it!
